name: Main CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Create Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: sweethymn/api:latest
          outputs: type=docker,dest=/tmp/output.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sweethymn/api
          path: /tmp/output.tar
  release:
    needs: build
    name: Release to repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: sweethymn/api
          path: /tmp
      - name: Load Docker image
        run: docker load --input /tmp/output.tar
      - name: Extract package version
        id: package
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Push to Amazon ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-3
          local-image: sweethymn/api:latest
          image: sweethymn/api:${{ steps.package.outputs.version }}
