name: Main CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Create a Docker image
        run: docker build --tag sweethymn/api .
  release:
    needs: build
    name: Release to repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Extract package version
        id: package
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Push to Amazon ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-3
          local-image: sweethymn/api
          image: sweethymn/api:${{ steps.package.outputs.version }}
